// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// s2n_C
NumericMatrix s2n_C(NumericMatrix x, LogicalMatrix y);
RcppExport SEXP _ggsea_s2n_C(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(s2n_C(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggsea_s2n_C", (DL_FUNC) &_ggsea_s2n_C, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggsea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
